# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        

      - deploy:
        name: Deploy to GH pages
        command: |
          TMP_DIR=$(mktemp -d)

          # Create bundle
          npm run build
          git commit -am "Create new bundle"

          # Copy build to temp folder
          cp -r ./build/ $TMP_DIR/build
          BUILD_FILES=`ls ./build`

          # Wipe out current site
          git checkout master
          git rm -rf .
          mv .git $TMP_DIR/.git
          rm -rf .
          mv $TMP_DIR/.git .git

          # Move new bundle to master
          mv -f $TMP_DIR/build/** ./

          # Create CNAME
          echo "astrocoders.com" > CNAME
          git add CNAME
          git add $BUILD_FILES

          # Commit and push changes
          git commit -m "New site"
          echo "\033[1;31mPushing new site to GitHub repo\n\033[0m"
          git push --force origin master
